name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

#    - name: Install UPX
#      run: sudo apt-get install -y upx

    - name: Go Get Govvv
      run: go get github.com/ahmetb/govvv

    - name: Go Get
      run: go get

    - name: Integration Tests
      run: go test -v

    - name: Build Linux
      run: go build -o mj -ldflags="$(govvv -flags -pkg $(go list ./version)) -s -w"

    - name: Test Build
      run: ./mj example/example.csv --sort
